config/routes.rb
Rails.application.routes.draw do
  resources :react_posts
  resources :hybrid_posts
  resources :rails_posts
  root 'home#index'# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/hybrid_post.rb
class HybridPost < ApplicationRecord
end

app/models/rails_post.rb
class RailsPost < ApplicationRecord
end

app/models/react_post.rb
class ReactPost < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/hybrid_posts_controller.rb
class HybridPostsController < ApplicationController
  before_action :set_hybrid_post, only: [:show, :edit, :update, :destroy]

  # GET /hybrid_posts
  # GET /hybrid_posts.json
  def index
    @hybrid_posts = HybridPost.all
  end

  # GET /hybrid_posts/1
  # GET /hybrid_posts/1.json
  def show
  end

  # GET /hybrid_posts/new
  def new
    @hybrid_post = HybridPost.new
  end

  # GET /hybrid_posts/1/edit
  def edit
  end

  # POST /hybrid_posts
  # POST /hybrid_posts.json
  def create
    @hybrid_post = HybridPost.new(hybrid_post_params)

    respond_to do |format|
      if @hybrid_post.save
        format.html { redirect_to @hybrid_post, notice: 'Hybrid post was successfully created.' }
        format.json { render :show, status: :created, location: @hybrid_post }
      else
        format.html { render :new }
        format.json { render json: @hybrid_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hybrid_posts/1
  # PATCH/PUT /hybrid_posts/1.json
  def update
    respond_to do |format|
      if @hybrid_post.update(hybrid_post_params)
        format.html { redirect_to @hybrid_post, notice: 'Hybrid post was successfully updated.' }
        format.json { render :show, status: :ok, location: @hybrid_post }
      else
        format.html { render :edit }
        format.json { render json: @hybrid_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hybrid_posts/1
  # DELETE /hybrid_posts/1.json
  def destroy
    @hybrid_post.destroy
    respond_to do |format|
      format.html { redirect_to hybrid_posts_url, notice: 'Hybrid post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hybrid_post
      @hybrid_post = HybridPost.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hybrid_post_params
      params.require(:hybrid_post).permit(:title, :content)
    end
end

app/controllers/rails_posts_controller.rb
class RailsPostsController < ApplicationController
  before_action :set_rails_post, only: [:show, :edit, :update, :destroy]

  # GET /rails_posts
  # GET /rails_posts.json
  def index
    @rails_posts = RailsPost.all
  end

  # GET /rails_posts/1
  # GET /rails_posts/1.json
  def show
  end

  # GET /rails_posts/new
  def new
    @rails_post = RailsPost.new
  end

  # GET /rails_posts/1/edit
  def edit
  end

  # POST /rails_posts
  # POST /rails_posts.json
  def create
    @rails_post = RailsPost.new(rails_post_params)

    respond_to do |format|
      if @rails_post.save
        format.html { redirect_to @rails_post, notice: 'Rails post was successfully created.' }
        format.json { render :show, status: :created, location: @rails_post }
      else
        format.html { render :new }
        format.json { render json: @rails_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rails_posts/1
  # PATCH/PUT /rails_posts/1.json
  def update
    respond_to do |format|
      if @rails_post.update(rails_post_params)
        format.html { redirect_to @rails_post, notice: 'Rails post was successfully updated.' }
        format.json { render :show, status: :ok, location: @rails_post }
      else
        format.html { render :edit }
        format.json { render json: @rails_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rails_posts/1
  # DELETE /rails_posts/1.json
  def destroy
    @rails_post.destroy
    respond_to do |format|
      format.html { redirect_to rails_posts_url, notice: 'Rails post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rails_post
      @rails_post = RailsPost.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rails_post_params
      params.require(:rails_post).permit(:title, :content)
    end
end

app/controllers/react_posts_controller.rb
class ReactPostsController < ApplicationController
  before_action :set_react_post, only: [:show, :edit, :update, :destroy]

  # GET /react_posts
  # GET /react_posts.json
  def index
    @react_posts = ReactPost.all
  end

  # GET /react_posts/1
  # GET /react_posts/1.json
  def show
  end

  # GET /react_posts/new
  def new
    @react_post = ReactPost.new
  end

  # GET /react_posts/1/edit
  def edit
  end

  # POST /react_posts
  # POST /react_posts.json
  def create
    @react_post = ReactPost.new(react_post_params)

    respond_to do |format|
      if @react_post.save
        format.html { redirect_to @react_post, notice: 'React post was successfully created.' }
        format.json { render :show, status: :created, location: @react_post }
      else
        format.html { render :new }
        format.json { render json: @react_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /react_posts/1
  # PATCH/PUT /react_posts/1.json
  def update
    respond_to do |format|
      if @react_post.update(react_post_params)
        format.html { redirect_to @react_post, notice: 'React post was successfully updated.' }
        format.json { render :show, status: :ok, location: @react_post }
      else
        format.html { render :edit }
        format.json { render json: @react_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /react_posts/1
  # DELETE /react_posts/1.json
  def destroy
    @react_post.destroy
    respond_to do |format|
      format.html { redirect_to react_posts_url, notice: 'React post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_react_post
      @react_post = ReactPost.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def react_post_params
      params.require(:react_post).permit(:title, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/hybrid_posts_helper.rb
module HybridPostsHelper
end

app/helpers/rails_posts_helper.rb
module RailsPostsHelper
end

app/helpers/react_posts_helper.rb
module ReactPostsHelper
end

app/views/home/index.html.erb
<h2>Select form type to view</h2>
<p>Inspect the forms with your browser's dev tools or see <a href="https://github.com/steveryan/react-rails_form_test">the github repo<a> to better understand the different implementations</p>

<%= link_to 'New Rails Post', new_rails_post_path %>
<br>
<%= link_to 'New React Post', new_react_post_path %>
<br>
<%= link_to 'New Hybrid Post', new_hybrid_post_path %>
</br>
<input type="text" name="example">
</br>
<div class="progress-bar">
  <div class="pw-strength" ></div>
</div>

app/views/hybrid_posts/_form.html.erb
<%= form_with(model: hybrid_post, local: true) do |form| %>
  <% if hybrid_post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(hybrid_post.errors.count, "error") %> prohibited this hybrid_post from being saved:</h2>

      <ul>
      <% hybrid_post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= react_component 'TitleFormOnly', { hybrid_post: @hybrid_post } %>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/hybrid_posts/edit.html.erb
<h1>Editing Hybrid Post</h1>

<%= render 'form', hybrid_post: @hybrid_post %>

<%= link_to 'Show', @hybrid_post %> |
<%= link_to 'Back', hybrid_posts_path %>

app/views/hybrid_posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Hybrid Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @hybrid_posts.each do |hybrid_post| %>
      <tr>
        <td><%= hybrid_post.title %></td>
        <td><%= hybrid_post.content %></td>
        <td><%= link_to 'Show', hybrid_post %></td>
        <td><%= link_to 'Edit', edit_hybrid_post_path(hybrid_post) %></td>
        <td><%= link_to 'Destroy', hybrid_post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Hybrid Post', new_hybrid_post_path %>

app/views/hybrid_posts/new.html.erb
<h1>New Hybrid Post</h1>

<%= render 'form', hybrid_post: @hybrid_post %>

<%= link_to 'Back', hybrid_posts_path %>

app/views/hybrid_posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @hybrid_post.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @hybrid_post.content %>
</p>

<%= link_to 'Edit', edit_hybrid_post_path(@hybrid_post) %> |
<%= link_to 'Back', hybrid_posts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ReactRailsFormTest</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/rails_posts/_form.html.erb
<%= form_with(model: rails_post, local: true) do |form| %>
  <% if rails_post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(rails_post.errors.count, "error") %> prohibited this rails_post from being saved:</h2>

      <ul>
      <% rails_post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/rails_posts/edit.html.erb
<h1>Editing Rails Post</h1>

<%= render 'form', rails_post: @rails_post %>

<%= link_to 'Show', @rails_post %> |
<%= link_to 'Back', rails_posts_path %>

app/views/rails_posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Rails Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rails_posts.each do |rails_post| %>
      <tr>
        <td><%= rails_post.title %></td>
        <td><%= rails_post.content %></td>
        <td><%= link_to 'Show', rails_post %></td>
        <td><%= link_to 'Edit', edit_rails_post_path(rails_post) %></td>
        <td><%= link_to 'Destroy', rails_post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Rails Post', new_rails_post_path %>

app/views/rails_posts/new.html.erb
<h1>New Rails Post</h1>

<%= render 'form', rails_post: @rails_post %>

<%= link_to 'Back', rails_posts_path %>

app/views/rails_posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @rails_post.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @rails_post.content %>
</p>

<%= link_to 'Edit', edit_rails_post_path(@rails_post) %> |
<%= link_to 'Back', rails_posts_path %>

app/views/react_posts/_form.html.erb
<%= react_component 'ReactForm', { react_post: @react_post } %>

app/views/react_posts/edit.html.erb
<h1>Editing React Post</h1>

<%= render 'form', react_post: @react_post %>

<%= link_to 'Show', @react_post %> |
<%= link_to 'Back', react_posts_path %>

app/views/react_posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>React Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @react_posts.each do |react_post| %>
      <tr>
        <td><%= react_post.title %></td>
        <td><%= react_post.content %></td>
        <td><%= link_to 'Show', react_post %></td>
        <td><%= link_to 'Edit', edit_react_post_path(react_post) %></td>
        <td><%= link_to 'Destroy', react_post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New React Post', new_react_post_path %>

app/views/react_posts/new.html.erb
<h1>New React Post</h1>

<%= render 'form', react_post: @react_post %>

<%= link_to 'Back', react_posts_path %>

app/views/react_posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @react_post.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @react_post.content %>
</p>

<%= link_to 'Edit', edit_react_post_path(@react_post) %> |
<%= link_to 'Back', react_posts_path %>